server:
  port: 8080

spring:
  application:
    name: workflow-task-lab

  sql:
    init:
      mode: always
  # H2 内存数据库
  datasource:
    url: jdbc:h2:mem:workflow_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # H2 控制台（浏览器访问 http://localhost:8080/h2-console）
  h2:
    console:
      enabled: true
      path: /h2-console

  # RabbitMQ 配置
  rabbitmq:
    host: localhost
    port: 5672
    username: workflow
    password: workflow123
    virtual-host: workflow_vhost
    listener:
      simple:
        acknowledge-mode: auto
        prefetch: 1
        retry:
          enabled: true
          initial-interval: 1000
          multiplier: 2.0
          max-attempts: 3
